services:
  tichu-ts-server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
      target: base
    container_name: tichu-ts-server
    volumes:
      - ./server/src:/home/node/app/server/src
      - ./shared:/home/node/app/shared
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: yarn run dev
  tichu-ts-client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
      target: base
    volumes:
      - ./client/src:/home/node/app/client/src
      - ./shared:/home/node/app/shared
    container_name: tichu-ts-client
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: yarn run dev
