services:
  tichu-ts-server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
      target: base
    container_name: tichu-ts-server
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: yarn run dev
