services:
  tichu-ts-server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
      target: base
    volumes:
      - ./server/src:/home/node/app/src
    container_name: tichu-ts-server
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: yarn run dev
