services:
  tichu-ts-server:
    build:
      target: production
    command: yarn run start
  tichu-ts-client:
    build:
      target: production
    expose:
      - '3001'
    ports:
      - '3001:3001'
    command: yarn run preview
  